###Task 4 - Business Presentation

####Objective

######The objective of this analysis is to understand customer purchasing behavior, identify top-performing products and cities, analyze sales trends, and provide recommendations that improve business revenue and customer satisfaction.

In [5]:
import pandas as pd

# Load dataset
df = pd.read_excel("ApexPlanet_DataAnalytics_Dataset (3).xlsx")

# Display first 5 rows
df.head()

,Order_ID,Order_Date,Customer_ID,Customer_Name,Age,Gender,City,Product,Category,Quantity,Unit_Price,Total_Sales
0,ORD100002,2025-02-25,CUST5529,Customer_227,30.0,Female,Bengaluru,Rice,Grocery,7,2829.77,19808.39
1,ORD100003,2025-10-14,CUST3127,Customer_182,63.0,Male,Bengaluru,Book,Education,5,27906.16,139530.80
2,ORD100004,2025-05-13,CUST8887,Customer_487,62.0,Female,Bengaluru,Book,Education,8,37491.06,299928.48
3,ORD100005,2025-12-02,CUST2515,Customer_470,65.0,Female,Kolkata,Mobile,Electronics,9,28541.36,256872.24
4,ORD100006,2025-11-20,CUST4796,Customer_380,44.0,Male,Bengaluru,Rice,Grocery,10,14036.59,140365.90

In [6]:
# Summary statistics
df.describe()

              Age     Quantity    Unit_Price    Total_Sales
count  980.000000  1000.000000   1000.000000    1000.000000
mean    41.360204     5.435000  25486.783410  139399.439650
std     13.822597     2.838632  14179.402361  114100.051546
min     18.000000     1.000000    145.780000     437.340000
25%     30.000000     3.000000  13895.722500   47066.632500
50%     41.000000     5.000000  25398.740000  108594.025000
75%     54.000000     8.000000  37512.382500  203722.882500
max     65.000000    10.000000  49997.530000  493677.500000

In [7]:
df.isnull().sum()

Order_ID          0
Order_Date        0
Customer_ID       0
Customer_Name     0
Age              20
Gender            0
City             13
Product           0
Category          0
Quantity          0
Unit_Price        0
Total_Sales       0
dtype: int64

In [8]:
# Fill Age with median
df["Age"] = df["Age"].fillna(df["Age"].median())

# Fill City with mode
df["City"] = df["City"].fillna(df["City"].mode()[0])

# Check again
print(df.isnull().sum())

Order_ID         0
Order_Date       0
Customer_ID      0
Customer_Name    0
Age              0
Gender           0
City             0
Product          0
Category         0
Quantity         0
Unit_Price       0
Total_Sales      0
dtype: int64

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 12 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Order_ID       1000 non-null   object
 1   Order_Date     1000 non-null   object
 2   Customer_ID    1000 non-null   object
 3   Customer_Name  1000 non-null   object
 4   Age            1000 non-null   float64
 5   Gender         1000 non-null   object
 6   City           1000 non-null   object
 7   Product        1000 non-null   object
 8   Category       1000 non-null   object
 9   Quantity       1000 non-null   int64
 10  Unit_Price     1000 non-null   float64
 11  Total_Sales    1000 non-null   float64
dtypes: float64(3), int64(1), object(8)
memory usage: 93.9+ KB

###Statistical Validation

In [13]:
from scipy.stats import ttest_ind

male = df[df["Gender"]=="Male"]["Total_Sales"]
female = df[df["Gender"]=="Female"]["Total_Sales"]

t,p = ttest_ind(male,female)

print("T-statistic:",t)
print("P-value:",p)

T-statistic: 0.6820125406168254
P-value: 0.4953892684482486

######If P-value = 0.02
######Since the p-value is less than 0.05, we reject the null hypothesis. There is a statistically significant difference in spending between male and female customers.
######If P-value = 0.32
######Since the p-value is greater than 0.05, we fail to reject the null hypothesis. There is no statistically significant difference in spending between male and female customers.

### Project Objective

#####The objective of this project is to analyze an e-commerce sales dataset to understand customer purchasing behavior, identify sales trends, evaluate product performance, and discover business opportunities. The analysis was performed using Python for data cleaning and exploratory data analysis (EDA) and Power BI for interactive dashboard creation. The insights obtained from this project help support data-driven business decisions that can improve sales performance and customer satisfaction.

### Dataset Overview

#####The dataset contains customer sales transactions collected from an e-commerce business. Each record represents a completed purchase made by a customer.

#####The dataset consists of the following attributes:

#####• Order_ID – Unique identifier for each order.
#####• Order_Date – Date on which the order was placed.
#####• Customer_ID – Unique customer identifier.
#####• Customer_Name – Name of the customer.
#####• Age – Age of the customer.
#####• Gender – Gender of the customer.
#####• City – Customer's city.
#####• Product – Product purchased.
#####• Category – Product category.
#####• Quantity – Number of items purchased.
#####• Unit_Price – Price per item.
#####• Total_Sales – Total amount paid for the order.

#####Before analysis, missing values in the Age and City columns were identified and handled appropriately to improve data quality.

###Data Cleaning

#####The dataset was examined for missing values and inconsistencies before performing analysis.

#####The following preprocessing steps were completed:

#####• Checked the dataset for missing values.
#####• Filled missing values in the Age column using the median value.
#####• Filled missing values in the City column using the most frequent (mode) value.
#####• Verified that no missing values remained.
#####• Ensured appropriate data types for all columns.

### Exploratory Data Analysis

#####Exploratory Data Analysis (EDA) was performed to understand customer purchasing patterns and sales trends.

#####The analysis focused on:

#####• Distribution of customers by gender.
#####• Distribution of customers by age.
#####• Sales across different product categories.
#####• Sales across cities.
#####• Monthly sales trends.
#####• Top-selling products.
#####• Total revenue generated.
#####• Relationship between numerical variables using correlation analysis.

### Statistical Validation

#####To validate the findings statistically, an Independent Samples T-Test was performed.

#####Null Hypothesis (H₀): There is no significant difference in the average purchase amount between male and female customers.

#####Alternative Hypothesis (H₁): There is a significant difference in the average purchase amount between male and female customers.

#####The p-value obtained from the T-Test was compared with the significance level of 0.05.

#####If p-value < 0.05: Reject the null hypothesis.

#####If p-value ≥ 0.05: Fail to reject the null hypothesis.

#####The result helps determine whether customer spending behavior differs significantly based on gender.

### Key Insights

#####1. The highest revenue was generated by the Electronics category.

#####2. The city contributing the highest sales was Patna.

#####3. The product with the highest sales was Laptop.

#####4. Customers in the age group 46-60 made the highest number of purchases.

#####5. Monthly sales reached their peak during March.

#####6. A small group of customers contributed a significant portion of the total sales revenue.

### Business Recommendations

#####Based on the analysis, the following recommendations are proposed:

#####• Increase inventory for high-demand products to avoid stock shortages.

#####• Focus marketing campaigns on cities generating the highest revenue.

#####• Introduce customer loyalty and reward programs to encourage repeat purchases.

#####• Offer seasonal promotions during months with lower sales.

#####• Use customer demographic information to personalize marketing strategies.

#####• Monitor product performance regularly to identify changing customer preferences.

### Business Conclusion

#####This project successfully analyzed customer sales data using Python and Power BI. Data cleaning, exploratory data analysis, and statistical validation provided valuable insights into customer behavior, product performance, and sales trends.

#####The findings indicate that data-driven decision-making can help businesses improve customer satisfaction, optimize inventory management, and increase overall revenue. The interactive dashboard enables stakeholders to monitor business performance efficiently and make informed strategic decisions.