##Task 1
####Data Immersion and Wrangling

## Objective

#####The objective of this project is to analyze a synthetic dataset, assess data quality, clean and transform the data.

In [16]:
import pandas as pd
#Reading the dataset file
df = pd.read_csv("synthetic_dataset.csv")
#removing extra whitespaces from column names
df.columns=df.columns.str.strip()

## Data Familiarization

#####In this step, we load the dataset and inspect its structure, columns, and basic statistics.

In [17]:
df.head()

  Category   Price    Rating         Stock  Discount
0      NaN  5548.0  1.870322           NaN       0.0
1      NaN  3045.0  4.757798           NaN      38.0
2      NaN  4004.0       NaN      In Stock       0.0
3      NaN  4808.0  1.492085           NaN      33.0
4      NaN  1817.0       NaN  Out of Stock      23.0

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4362 entries, 0 to 4361
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Category  1614 non-null   object
 1   Price     4188 non-null   float64
 2   Rating    2312 non-null   float64
 3   Stock     3010 non-null   object
 4   Discount  3970 non-null   float64
dtypes: float64(3), object(2)
memory usage: 170.5+ KB

In [7]:
df.describe()

             Price       Rating     Discount
count  4188.000000  2312.000000  3970.000000
mean   5016.970630     3.038293    24.516625
std    2839.984813     1.143074    14.347164
min     102.000000     1.000366     0.000000
25%    2628.250000     2.069490    12.000000
50%    4996.500000     3.082060    25.000000
75%    7418.000000     4.008620    37.000000
max    9999.000000     4.997818    49.000000

## Data Quality Assessment

#####The dataset was checked for:
#####- Missing values
#####- Duplicate records
#####- Incorrect data types

In [8]:
df.isnull().sum()

Category    2748
Price        174
Rating      2050
Stock       1352
Discount     392
dtype: int64

In [9]:
df.duplicated().sum()

np.int64(15)

###Data Cleaning and Transforming

#####Missing values can affect analysis accuracy. Therefore, null values were identified and handled appropriately.

In [11]:
df = df.drop_duplicates()

In [12]:
df['Category'] = df['Category'].fillna(df['Category'].mode()[0])
df['Price'] = df['Price'].fillna(df['Price'].mean())
df['Rating'] = df['Rating'].fillna(df['Rating'].median())
df['Discount'] = df['Discount'].fillna(df['Discount'].mean())
df['Stock'] = df['Stock'].fillna(0)

###Cleaned Dataset

In [13]:
df.isnull().sum()

Category    0
Price       0
Rating      0
Stock       0
Discount    0
dtype: int64

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4347 entries, 0 to 4361
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Category  4347 non-null   object
 1   Price     4347 non-null   float64
 2   Rating    4347 non-null   float64
 3   Stock     4347 non-null   object
 4   Discount  4347 non-null   float64
dtypes: float64(3), object(2)
memory usage: 203.8+ KB

In [15]:
df.to_csv("cleaned_dataset.csv", index=False)